### PR TITLE
update conf

### PR DESCRIPTION
**Pull request by ntanh2**
add my Validator: emoneyvaloper1zvccz5hzyqzxs5jtx9hve27jwc6c3nmqnh09nc

### CODE REVIEW

**Comment by mdyring** [comment]
Please provide information on
1. Past experience on operating validators, which networks, links to block explorers
2. Link to validator website / team background
3. Overview of the infrastructure setup

**Comment by ntanh2** [comment]
I'm operating validators for few Cosmos-based chains: Sifchain. Our team have been working in the app - development field since 2010. We built system on Linux, our server is stable and reliable. The website is under maintaining and will be back after few days

**Comment by ntanh2** [comment]
Our team have been working in the app - development field since 2010. We built system on Linux too. We also have a Sifchain server

**Comment by mdyring** [comment]
Appears offline.

**Pull request closed without merging**
