### PR TITLE
Add validator to configuration.json

### PR DESCRIPTION
**Pull request by nkhanh386**
My Validator: Huge Block, add: emoneyvaloper1sg7gfku9tjy3sr9h5rxk2xwatkmh7r9nxjt603

### CODE REVIEW

**Comment by nkhanh386** [comment]
My Validator: Huge Block, please Add validator to configuration.json

**Comment by mdyring** [comment]
Please provide information on:

- Past experience on operating validators, which networks, links to block explorers
- Link to validator website / team background / socials
- Overview of the infrastructure setup

**Comment by nkhanh386** [comment]
> Please provide information on:
> 
> * Past experience on operating validators, which networks, links to block explorers
> * Link to validator website / team background / socials
> * Overview of the infrastructure setup

Our team have been working in the app - development field since 2010. We built system on Linux too. We also have a Sifchain server. The website's name: http://hugeblockchain.info/

**Comment by mdyring** [comment]
Appears to be offline.

**Pull request closed without merging**
